#!/usr/bin/env python3
"""PreToolUse (Edit|Write) hook: block hand-edits to generated output.

Three directories are regenerated by running a task, not by hand-editing the
files CumulusCI writes into them. An edit made directly in one of them looks
like it "sticks" until the generator next runs and silently overwrites it,
which is a worse failure than refusing the edit up front.

  * `unpackaged/post_ux/**` -- written by `assemble_and_deploy_ux`
    (tasks.rlm_ux_assembly.AssembleAndDeployUX) and the writeback flow
    (tasks.rlm_writeback_ux). Re-run those to change UX metadata.
  * `datasets/bre/**` -- written by `export_bre_rule_library`
    (tasks.rlm_bre.ExportBRE). Re-run that to refresh a BRE export.
  * `datasets/dx/**` -- runtime extraction output per AGENTS.md's data-layout
    note; not tracked source.

Self-contained by requirement: claude-code-action restores `.claude/` from the
base ref before running, so this hook cannot assume any sibling script (this
repo's own `tasks/` package, `scripts/ai/*`) is present or importable at that
point -- stdlib only.

Matching is done on normalized, segment-anchored path fragments (e.g.
``(^|/)unpackaged/post_ux/``) rather than a computed repo-relative path, so it
is immune to *how* the absolute path was spelled: forward or back slashes, a
`cwd` that is the repo root vs. some subdirectory of it (or missing
entirely), drive-letter case (`c:` vs `C:`), or an MSYS/Git-Bash style
`/c/Users/...` path. `CLAUDE_PROJECT_DIR` is used only to resolve a
*relative* `file_path` against a base directory before normalizing; matching
itself never depends on successfully deriving a clean relative path.

Exit 2 blocks the edit and puts the reason in Claude's context (hooks guide,
exit-code-2 semantics). Exit 0 is silent and lets the normal permission flow
run. Any error reading/parsing stdin also exits 0: a hook that fails open on
its own malfunction is a nuisance; one that fails *closed* would block every
Edit/Write repo-wide the moment its assumptions about the payload shape drift.
"""
from __future__ import annotations

import json
import os
import re
import sys

PROTECTED = [
    ("unpackaged/post_ux",
     "generated by assemble_and_deploy_ux / the UX writeback flow "
     "(tasks.rlm_ux_assembly.AssembleAndDeployUX, tasks.rlm_writeback_ux) -- "
     "re-run the generator instead of hand-editing its output"),
    ("datasets/bre",
     "generated by the export_bre_rule_library task "
     "(tasks.rlm_bre.ExportBRE) -- re-run it to refresh this export"),
    ("datasets/dx",
     "runtime extraction output, not tracked source -- regenerate it "
     "instead of hand-editing"),
]

_MSYS_DRIVE_RE = re.compile(r"^/([A-Za-z])/(.*)$")
_WIN_DRIVE_RE = re.compile(r"^[A-Za-z]:/")

_PROTECTED_PATTERNS = [
    (re.compile(r"(^|/)" + re.escape(prefix) + r"/", re.IGNORECASE), prefix, reason)
    for prefix, reason in PROTECTED
]


def _normalize(path: str) -> str:
    """Forward-slash the path and canonicalize drive-letter spellings.

    Handles native Windows (`C:\\...` / `c:\\...`), POSIX-style forward
    slashes on Windows (`C:/...`), and MSYS/Git-Bash (`/c/...`) so all three
    compare equal after normalization.
    """
    normalized = path.replace("\\", "/")
    msys_match = _MSYS_DRIVE_RE.match(normalized)
    if msys_match:
        normalized = f"{msys_match.group(1).upper()}:/{msys_match.group(2)}"
    elif _WIN_DRIVE_RE.match(normalized):
        normalized = normalized[0].upper() + normalized[1:]
    return normalized


def _is_absolute(path: str) -> bool:
    return path.startswith("/") or bool(_WIN_DRIVE_RE.match(path))


def _resolved_path(file_path: str, cwd: str | None) -> str:
    """Best-effort absolute, normalized form of `file_path`.

    A relative `file_path` is joined against `cwd` (from the hook payload)
    or, failing that, `CLAUDE_PROJECT_DIR`. If neither is available the
    relative path is normalized and matched as-is -- still correct for
    segment-anchored matching as long as the relevant segments are present.
    """
    norm_file = _normalize(file_path)
    if _is_absolute(norm_file):
        return norm_file

    base = cwd or os.environ.get("CLAUDE_PROJECT_DIR")
    if base:
        norm_base = _normalize(base).rstrip("/")
        return f"{norm_base}/{norm_file}"
    return norm_file


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError, OSError):
        return 0

    file_path = payload.get("tool_input", {}).get("file_path")
    if not file_path:
        return 0

    resolved = _resolved_path(file_path, payload.get("cwd"))

    for regex, prefix, reason in _PROTECTED_PATTERNS:
        if regex.search(resolved):
            sys.stderr.write(
                f"Blocked: {file_path} is under {prefix}/, which is {reason}.\n")
            return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
