#!/usr/bin/env python3
"""Generate a minimal, mechanically-accurate README.md for an SFDMU plan directory.

Derives the object table (Object, Pass, Operation, External ID, Records) and a
file listing straight from export.json + the plan's CSVs, reusing
check_plan_readme_consistency.py's own parsing (object_name/load_plan/csv_index/
resolve_pass_csv) rather than re-deriving it — so the generated README is guaranteed
to pass that check, and stays the same defect class it isn't (see packs 160-163:
duplicated ad hoc SOQL/export.json parsing drifts from the canonical parser).

An object that carries a different operation/externalId per pass (Upsert in Pass
1, Update in Pass 2, say) gets one row per pass — the plan's own pass boundaries,
read straight off export.json's objectSets order, not folded into a single row
that would only show the first pass's behavior.

This intentionally does NOT attempt the narrative prose (flow integration, pass
architecture, portability notes) that hand-written plan READMEs carry — that
requires domain knowledge no script has. The generated table+listing lives
between two HTML-comment markers; regenerating an EXISTING README replaces only
that block and leaves everything outside it — narrative sections included —
untouched. A README with no markers (a legacy hand-written one, or one a prior
run of this script never touched) is left alone unless --force is passed, which
replaces the whole file and discards anything outside the block.

Usage:
  python scripts/ai/generate_plan_readme.py datasets/sfdmu/mfg/en-US/mfg-billing
  python scripts/ai/generate_plan_readme.py --all-missing   # every tracked plan with
                                                              # export.json and no README.md
  python scripts/ai/generate_plan_readme.py <plan_dir> --force  # replace a marker-less README wholesale
"""
from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from check_plan_readme_consistency import (  # noqa: E402
    csv_index,
    display_rel,
    find_plan_dirs,
    load_export_data,
    load_plan,
    resolve_pass_csv,
    tracked_plan_dirs,
)
from validate_sfdmu_v5_datasets import SFDMUValidator  # noqa: E402

BEGIN_MARKER = "<!-- generate_plan_readme:begin -->"
END_MARKER = "<!-- generate_plan_readme:end -->"

# load_plan() now resolves `operation` through SFDMUValidator._resolve_operation, which
# returns the canonical lowercase enum name (matching SFDMU_OPERATION_BY_INDEX) rather
# than the plan's own literal string — display casing matching the enum names SFDMU
# itself uses (Enumerations.js) so the table doesn't render "upsert" where every
# hand-written README says "Upsert".
_OPERATION_DISPLAY = {
    "insert": "Insert", "update": "Update", "upsert": "Upsert", "readonly": "Readonly",
    "delete": "Delete", "deletesource": "DeleteSource", "deletehierarchy": "DeleteHierarchy",
    "harddelete": "HardDelete", "unknown": "Unknown",
}


def _escape_cell(value: str) -> str:
    """Table-safe a raw value before interpolating it into a `| a | b |` row. Substitutes
    the ASCII pipe for the fullwidth lookalike '｜' rather than backslash-escaping it
    (the CommonMark convention) — check_plan_readme_consistency.py's own
    parse_object_tables() splits a row on a literal '|' with no escape-awareness, so a
    backslash-escaped pipe would still desync ITS column count on re-check, even though
    it renders fine. Every other cell (name, pass, count) is script-derived and
    pipe/newline-free, but operation can render load_plan()'s
    `Unresolvable(<raw value>!r)` sentinel — a raw repr of whatever malformed value
    export.json actually declared, free to contain '|' or a newline (round 16 of PR
    #406's review, pack 147). Applied unconditionally, not just for the sentinel case,
    since externalId is also a raw string read straight from export.json with no
    character restriction of its own."""
    return value.replace("|", "｜").replace("\n", " ")


BLOCK_TEMPLATE = """{begin}
<!-- Generated by scripts/ai/generate_plan_readme.py from export.json + CSVs.
     Regenerate with the same command after changing this plan's objects,
     operations, or externalIds rather than hand-editing this block — content
     outside these markers (narrative sections) is preserved on regeneration. -->

## Objects

| # | Object | Pass | Operation | External ID | Records |
|---|--------|------|-----------|-------------|---------|
{rows}
{notes}
## Required source CSVs

<!-- Only CSVs a live-writable declaration must load. A source-free declaration's CSV
     is not required and is omitted here even if one ships: a Readonly/Delete object
     resolves from the target org, and an excluded object is skipped entirely before
     load. -->

```
{files}
```
{end}"""

FRESH_TEMPLATE = """# {title} Data Plan

{block}
"""


def generate_block(plan_dir: str) -> str:
    export_json = os.path.join(plan_dir, "export.json")
    data = load_export_data(export_json)
    plan = load_plan(export_json, data=data)
    # JS truthiness, not plain Python bool() — SFDMU reads this the same way it reads
    # excluded/deleteOldData, where `[]`/`{}` are truthy in JS but falsy in Python
    # (see validate_sfdmu_v5_datasets.py's _is_js_truthy docstring).
    use_separated = SFDMUValidator._is_js_truthy(data.get("useSeparatedCSVFiles"))
    csv_idx = csv_index(plan_dir)

    rows = []
    files: dict[str, int] = {}
    count_cache: dict[str, int] = {}
    row_num = 0
    writable_missing_csv = False
    # (object, pass) -> count of LIVE (non-excluded) declarations, to surface a same-pass
    # duplicate as a visible note rather than two table rows indistinguishable in every
    # compared cell (todo pack 165). The Object cell can't carry the marker —
    # check_plan_readme_consistency keys its row match on that exact string, so an
    # annotated name reads as a phantom object — so the note lives beneath the table where
    # the checker's row parser doesn't look. Two skips keep the note firing on EXACTLY the
    # set validate_sfdmu_v5_datasets.py._check_same_pass_duplicates gates (live > 1), so it
    # never cites a gating HIGH the validator does not raise:
    #   - Excluded declarations: SFDMU drops an excluded ScriptObject before task creation,
    #     so a live+excluded pair is a single load, not a doubled one. `variant["excluded"]`
    #     is already a resolved bool (load_plan runs it through _is_js_truthy).
    #   - Unparseable-query declarations: object_name() keeps a malformed query under an
    #     `Unparseable(...)` sentinel name so its row stays visible, but the validator's
    #     `_all_pass_configs` drops it (`_extract_object_name` returns "" → declaration
    #     skipped). Counting the sentinel would note a duplicate the validator never gates.
    #     That sentinel is the only non-object key object_name() emits, so its prefix
    #     identifies exactly the dropped set.
    # Keyed case-INSENSITIVELY, matching the validator: Salesforce object API names are
    # case-insensitive, so `Widget__c` and `widget__c` in one pass are one target object
    # loaded twice. The value lists the exact casings seen for display.
    same_pass_counts: dict[tuple[str, int], list[str]] = {}
    for name, variants in plan.items():
        is_unparseable = name.startswith("Unparseable(")
        for variant in variants:
            row_num += 1
            pass_no = variant["pass"]
            if not variant["excluded"] and not is_unparseable:
                same_pass_counts.setdefault((name.lower(), pass_no), []).append(name)
            # load_plan() already resolves "absent key" to "readonly" and a present-
            # but-unresolvable value to a distinct "Unresolvable(...)" sentinel — never
            # "" — so there is no separate absent-key fallback needed here.
            op = _escape_cell(_OPERATION_DISPLAY.get(variant["operation"], variant["operation"]))
            ext_id = _escape_cell(variant["externalId"]) or "—"
            count, relpath = resolve_pass_csv(plan_dir, csv_idx, use_separated, name, pass_no, count_cache)
            # A Readonly object resolves from the target ORG, not a loaded file (pack 151):
            # its record count is *org records*, not a load dependency, even when an optional
            # CSV happens to ship. This generator is offline and has no org count, and
            # relabeling the optional CSV's row count as an org count would bake in a number
            # that's never validated and silently wrong whenever the org and CSV differ
            # (PR #445 review, codex 4022218302). Emit `—` (unknown): the checker never
            # file-matches a `—` row, so deleting that optional CSV stays correctly silent. A
            # human who has a real org count may hand-write `N (org)`, which the checker reads
            # (ORG_COUNT_RE) and exempts from file matching; the generator never mints one.
            if variant["operation"] == "readonly":
                records = "—"
            else:
                records = str(count) if count is not None else "—"
            rows.append(f"| {row_num} | {_escape_cell(name)} | {pass_no} | {op} | {ext_id} | {records} |")
            # Calls the validator's own centralized rule instead of re-deriving it as a
            # second, independent copy of "Readonly AND Delete owe no CSV" (round 17 of
            # PR #406's review, pack 147) — the same drift-avoidance reason this module
            # already imports _is_js_truthy/_resolve_operation/_normalized_object_sets.
            # Safe to call on `variant` directly, not the raw export.json dict
            # `_is_live_writable` normally takes: `variant["excluded"]` is already a
            # resolved bool (via _is_js_truthy) and `variant["operation"]` is already a
            # canonical lowercase enum name or the "Unresolvable(...)" sentinel — both are
            # idempotent inputs to `_is_live_writable`'s own `_is_js_truthy`/
            # `_resolve_operation` calls (verified: matches the prior inline check on
            # every case, including excluded, Readonly, Delete, Unresolvable, and a plain
            # writable operation).
            writable = SFDMUValidator._is_live_writable(variant)
            # Only a live-writable declaration's CSV is REQUIRED, so only it is emitted into the
            # Files listing — which the checker asserts must exist on disk (file-structure pass).
            # A source-free declaration's CSV, if one ships, is optional — a Readonly/Delete object
            # resolves from the target org (not the file), and an excluded declaration is skipped
            # entirely before load — so listing it would make deleting that optional CSV a "no such
            # CSV on disk" error, contradicting the row rendering it `—` (PR #445 review, copilot
            # 4022308405). A file SHARED by a writable declaration is still listed: that writable
            # pass reaches this branch for the same relpath and adds it. `not in files` keeps each
            # physical file listed once.
            if writable and relpath is not None and relpath not in files:
                files[relpath] = count
            elif writable and relpath is None:
                writable_missing_csv = True

    # A literal space precedes "#" so a path >= 40 chars (e.g. an objectset_source/
    # object-set-N/ override) still gets a separator — ljust alone pads only when
    # shorter, so a plain `+` concatenation ran the two together for long paths.
    file_lines = [f"{p.ljust(40)} # {n} record{'s' if n != 1 else ''}" for p, n in files.items()]
    if writable_missing_csv:
        # Distinct from the Readonly/excluded case below — a writable, non-excluded
        # object legitimately owes a CSV here and doesn't have one. That's a plan
        # defect for validate_sfdmu_v5_datasets.py to flag, not evidence the plan has
        # no CSVs by design. Appended regardless of whether file_lines is otherwise
        # empty — a plan with some real CSVs and one missing one previously dropped
        # the missing object with no signal at all, since this branch only ran when
        # file_lines was empty.
        file_lines.append("(missing CSV — a writable, non-excluded object has none; see validate_sfdmu_v5_datasets.py)")
    if file_lines:
        files_text = "\n".join(file_lines)
    else:
        files_text = ("(no required CSVs — every object is source-free: "
                      "Readonly, Delete, or excluded)")

    # A same-pass duplicate declaration renders as two rows identical in every compared
    # cell (only the leading # differs). Surface it explicitly — the underlying plan is a
    # gating HIGH in validate_sfdmu_v5_datasets.py (SFDMU loads the object once per
    # declaration and resolves lookups to the last), so the note points there.
    dups = sorted((sorted(set(names))[0], pass_no, len(names), sorted(set(names)))
                  for (_lower, pass_no), names in same_pass_counts.items() if len(names) > 1)
    if dups:
        listed = "; ".join(
            f"{_escape_cell('/'.join(exact) if len(exact) > 1 else display)} (Pass {pass_no} ×{n})"
            for display, pass_no, n, exact in dups)
        notes = ("\n> **⚠ Same-pass duplicate declaration(s):** " + listed + ". "
                 "SFDMU loads the object once per declaration and resolves lookups to the "
                 "last — almost certainly an authoring mistake; see "
                 "validate_sfdmu_v5_datasets.py (gating HIGH).\n")
    else:
        notes = ""

    return BLOCK_TEMPLATE.format(
        begin=BEGIN_MARKER,
        end=END_MARKER,
        rows="\n".join(rows),
        notes=notes,
        files=files_text,
    )


def _write_fresh(readme: str, plan_dir: str, block: str) -> None:
    content = FRESH_TEMPLATE.format(title=os.path.basename(plan_dir), block=block)
    with open(readme, "w", encoding="utf-8") as fh:
        fh.write(content)


def write_readme(plan_dir: str, force: bool = False) -> tuple[bool, str]:
    """Returns (wrote, message)."""
    readme = os.path.join(plan_dir, "README.md")

    if not os.path.isfile(readme):
        _write_fresh(readme, plan_dir, generate_block(plan_dir))
        return True, f"wrote {display_rel(readme)} (new)"

    with open(readme, encoding="utf-8") as fh:
        existing = fh.read()

    begin_idx = existing.find(BEGIN_MARKER)
    end_idx = existing.find(END_MARKER)
    # end_idx > begin_idx, not just "both present" — a README with the markers out of
    # order (bad manual edit, bad merge) must fall through to --force/skip below rather
    # than crash trying to split a block boundary that doesn't actually exist. Likewise a
    # DUPLICATED marker (existing.count() > 1) — find() only ever sees the first
    # occurrence, so splicing on it would silently fold any real content between a stray
    # extra BEGIN and the real one out of the file instead of raising anything.
    has_clean_markers = (begin_idx != -1 and end_idx > begin_idx
                          and existing.count(BEGIN_MARKER) == 1 and existing.count(END_MARKER) == 1)

    if not has_clean_markers and not force:
        return False, (
            f"skip {display_rel(readme)} — has no generate_plan_readme markers; "
            "regenerating would discard hand-written content. Pass --force to replace it wholesale."
        )

    # Only reached when a write is actually about to happen — generate_block() does a
    # full CSV directory walk plus a row-count of every referenced CSV, wasted work on
    # the skip path above.
    block = generate_block(plan_dir)
    if has_clean_markers:
        pre = existing[:begin_idx]
        post = existing[end_idx + len(END_MARKER):]
        content = pre + block + post
        with open(readme, "w", encoding="utf-8") as fh:
            fh.write(content)
        return True, f"wrote {display_rel(readme)} (regenerated marked block, narrative preserved)"

    _write_fresh(readme, plan_dir, block)
    return True, f"wrote {display_rel(readme)} (--force: replaced whole file, no markers found)"


def find_missing() -> list[str]:
    """Delegates to check_plan_readme_consistency's own discovery rather than
    re-walking datasets/sfdmu here — a second independent walk could silently
    diverge from it (e.g. an exclusion rule added to one and not the other)."""
    _with_readme, no_readme = find_plan_dirs([])
    return no_readme


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("targets", nargs="*", help="Plan dirs to generate/regenerate a README for")
    ap.add_argument("--all-missing", action="store_true", help="Generate for every tracked plan with export.json and no README.md")
    ap.add_argument("--force", action="store_true", help="Replace a marker-less existing README wholesale instead of skipping it")
    args = ap.parse_args()

    if args.targets and args.all_missing:
        # Without this check, `targets = find_missing()` below silently overwrites
        # args.targets — a caller naming a specific plan AND passing --all-missing would
        # get every tracked README-less plan regenerated instead of just the one named,
        # with no warning that their explicit argument was dropped.
        ap.error("targets and --all-missing are mutually exclusive")

    targets = args.targets
    if args.all_missing:
        targets = find_missing()
        # Only tracked plans — skip local/gitignored scratch dirs (e.g. datasets/sfdmu/test/).
        # Reuses check_plan_readme_consistency's own tracked_plan_dirs() rather than a
        # second, independent git-tracked-ness check that could silently diverge from it.
        targets = tracked_plan_dirs(targets)

    if not targets:
        print("No targets.", file=sys.stderr)
        return 1

    ok = True
    for t in targets:
        wrote, message = write_readme(os.path.abspath(t), force=args.force)
        print(message)
        ok = ok and wrote
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
